[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }



[[redirects]]
  from = "/*"
  to = "/index"
  status = 404
  
  
  
[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 401
  
  
  
[[redirects]]  
  from = "/*"
  to = "/auth/index.html"
  status = 200
  conditions = {Role = ["admin"]}
