[build]
  Functions = "functions"
  command = "yarn run build"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[[redirects]]
  from = "/"
  to = "/auth/*"
  status = 200
  force = true
  conditions = {Role = ["admin"]}
  
  
[[redirects]]
  from = "/auth/*"
  to = "/index.html"
  status = 401
  force = true
