[build]
  Functions = "functions"
  command = "yarn run build && cp _redirects dist/_redirects"
  publish = "dist"
  environment = { NODE_VERSION = "8.9.0" }



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
